name: Dry Run Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dryrun:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas prettytable docopt

    - name: Create mock output files
      run: |
        echo "recovery group  pdisk" > not_ok_pdisk.txt
        echo "rg1             pdisk1" >> not_ok_pdisk.txt
        echo "recovery group  pdisk" > replace_pdisk.txt
        echo "rg1             pdisk1" >> replace_pdisk.txt

    - name: Run script in dryrun mode
      run: |
        python3 mmvdisk_replace.py --dryrun
